### Hello! This is the project which shows how to do linear algebra math by using Python. This project focuses on the basic knowledge about matrices and vectors including:
- Create a matrix and verify the dimension, size and entries.
- Add a column/row into the given matrix with "Append" or "Concatenate".
- Matrix operations (Addition,Multiplication, and Dot Product)
- Matrix Inverse and Determinants
- Reduce Row Echelon Form (RREF)

In [13]:
import numpy as np
import scipy.linalg as la
from sympy import * 

### Create a matrix and verify the info (dim, size, and entries)

In [14]:
# Create a matrix A (3x3)
A = np.array([ [2,4,5],[1,3,4],[4,5,6]])
print("The matrix A is \n",A)
# Verify the dimensions, shape, and size of the array
print("The dimension of matrix A is",A.ndim)
print("The shape of matrix A is",A.shape)
print("The total number of entries are:",A.size)


The matrix A is 
 [[2 4 5]
 [1 3 4]
 [4 5 6]]
The dimension of matrix A is 2
The shape of matrix A is (3, 3)
The total number of entries are: 9


In [15]:
# Create an array list from a to b with a range of c by np.arange(a,b,c)
K = np.arange(0,27,3)
# Reconstruct the above list into another matrix dimension by reshape(rows,columns) 
K = K.reshape(3,3)
print("The matrix K is \n",K)

The matrix K is 
 [[ 0  3  6]
 [ 9 12 15]
 [18 21 24]]


### Add a column into the given matrix

In [16]:
B = np.array([[2],[3],[4]])
# Add a column into the array by using "append"
C = np.append(A,B,axis=1)
print("After appending a new column B, C is: \n",C)
D = np.concatenate((A,B),axis=1)
print("After concatenating matrix B and A, D is: \n",D)

After appending a new column B, C is: 
 [[2 4 5 2]
 [1 3 4 3]
 [4 5 6 4]]
After concatenating matrix B and A, D is: 
 [[2 4 5 2]
 [1 3 4 3]
 [4 5 6 4]]


### Add a row into the given matrix

In [17]:
E = np.array([2,3,4,5])
# Add a new row into the array C by using "append"
F = np.append(C,[E],axis=0)
print("After appending a new row E into C, we have: \n",F)
# Add a new row into the array by using "concatenate"
G = np.concatenate([C,[E]],axis=0)
print("After concatenating matrix E and C, we have: \n",G)

After appending a new row E into C, we have: 
 [[2 4 5 2]
 [1 3 4 3]
 [4 5 6 4]
 [2 3 4 5]]
After concatenating matrix E and C, we have: 
 [[2 4 5 2]
 [1 3 4 3]
 [4 5 6 4]
 [2 3 4 5]]


### Operations among matrices (Transpose, Dot Product, Addition, and Power)

In [18]:
# Transpose a matrix
A_T = A.T
print("The matrix A transpose is: \n",A_T)
# Do arithmatic operations between A and K matrices
B = K + A
print("The sum of matrices (A and K) is: \n",B)
# Dot product between two matrices
print("Dot product of matrices (A and K) is \n",A@K)
# Raise a power for matrix A
print("The square of matrix A is \n",A*A)

The matrix A transpose is: 
 [[2 1 4]
 [4 3 5]
 [5 4 6]]
The sum of matrices (A and K) is: 
 [[ 2  7 11]
 [10 15 19]
 [22 26 30]]
Dot product of matrices (A and K) is 
 [[126 159 192]
 [ 99 123 147]
 [153 198 243]]
The square of matrix A is 
 [[ 4 16 25]
 [ 1  9 16]
 [16 25 36]]


### Matrix Inverse and Determinant

In [19]:
# Find matrix inverse by linalg function
print("The inverse of matrix A is \n",la.inv(A))
# Find the determinant of matrix
print("The determinant of matrix A  is \n",la.det(A))
A1 = la.inv(A)
#Dot product of a matrix and its identity
print("The dot product of a matrix and its invesse: \n",np.rint(A.dot(A1)))

The inverse of matrix A is 
 [[-2.  1.  1.]
 [10. -8. -3.]
 [-7.  6.  2.]]
The determinant of matrix A  is 
 1.000000000000002
The dot product of a matrix and its invesse: 
 [[ 1.  0.  0.]
 [-0.  1.  0.]
 [-0.  0.  1.]]


### Reduce Row Echelon Form (RREF)

In [20]:
# Using sympy library to calculate rref
# Find RREF for a mtrix
A_RREF = Matrix(A).rref()
# It will retrieve two tuples: a rref form and indices of pivot column
A1 = A_RREF[0]
# To get a rref form only, find the first tuple
A1

Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

In [21]:
myMatrix = Matrix([[1, 0, 7, 3, 2], [0, 6, 4, 7, 3], [7,-1, -3, -5, -4]])

# Using sympy.rref() method to find rref
matrix_rref = myMatrix.rref()
	
print("The Row echelon form of given matrix and the pivot column is: {}".format(matrix_rref))


The Row echelon form of given matrix and the pivot column is: (Matrix([
[1, 0, 0,  -17/44, -17/44],
[0, 1, 0,   65/77,   3/11],
[0, 0, 1, 149/308,  15/44]]), (0, 1, 2))
